version: "2"

services:
 web_server_template:
  build:
   context: .
   dockerfile: ./nodeApp/Dockerfile
  ports:
   - "0.0.0.0:8001:8001"
  container_name: web_application_template
  depends_on:
    - mongo
 mongo:
  image: mongo
  ports:
   - "27017:27017"
networks:
  back-tier:
   driver: bridge
